apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-deploy
spec:
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - name: demoapp
        image: demok8acr.azurecr.io/demok8:56
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 80